### ISSUE TITLE
Getting error when running pipeline

### ISSUE THREAD

**Issue by rachelss** [stevenhwu/MiDiMu#4]
Parse calls from trio
Parse calls from single
Get variable sites
Traceback (most recent call last):
  File "./get_base_counts_trio.py", line 117, in <module>
    with gzip.open(variable_site_file, 'rb') as ref_data:
AttributeError: GzipFile instance has no attribute '__exit__'

**Comment by stevenhwu** [comment]
Can you please let me know the OS version and python version??
And can you please run the following code in python see what do you get?
```python
import gzip
dir(gzip)
dir(gzip.GzipFile)
```

**Comment by rachelss** [comment]
Oops, sorry was running python 2.6 as cluster default. Works fine with 2.7
